title: cool title
author: MagicVin
email: v.xin.zhang@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A new site for me!

# social links
twitter_username: null # DO NOT include the @ character, or else the build will fail!
github_username:  MagicVin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
